server:
  port: 8084

  r2dbc:
    url: r2dbc:postgresql://${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

sqlite:
  url: "jdbc:sqlite:/path/to/your/db.sqlite"